# Generated by Django 4.0.2 on 2022-02-18 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('unique_identifier', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('number1', models.IntegerField()),
                ('number2', models.IntegerField()),
                ('answer', models.IntegerField(blank=True)),
            ],
        ),
    ]
