# Generated by Django 4.0.2 on 2022-02-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='answer',
            field=models.IntegerField(null=True),
        ),
    ]
